export type CarbonGrade = "A" | "B" | "C" | "D" | "E" | "F" | "G"

export type VehicleCategory =
  | "Citadine"
  | "Berline"
  | "SUV"
  | "Break"
  | "Coupe"
  | "Monospace"
  | "Utilitaire"

export interface VinHistoryEntry {
  date: string
  event: string
  mileage: number
  location: string
  status: "ok" | "warning" | "info"
}

export interface Car {
  id: string
  brand: string
  model: string
  year: number
  price: number
  mileage: number
  fuel: string
  co2: number
  carbonGrade: CarbonGrade
  transmission: string
  power: string
  image: string
  location: string
  category: VehicleCategory
  doors: number
  seats: number
  trunkVolume: number // in liters
  color: string
  drivetrain: "Traction" | "Propulsion" | "Integrale"
  euroNorm: "Euro 6d" | "Euro 6" | "Euro 5"
  autonomy: number // km for electric, 0 for others
  cylinders: string // e.g. "1.6L 4 cyl" or "Moteur electrique"
  weight: number // kg
  vin: string // Vehicle Identification Number (17 characters)
  vinHistory: VinHistoryEntry[]
}

export const vehicleCategoryConfig: Record<
  VehicleCategory,
  { label: string; icon: string }
> = {
  Citadine: { label: "Citadine", icon: "city" },
  Berline: { label: "Berline", icon: "sedan" },
  SUV: { label: "SUV / Crossover", icon: "suv" },
  Break: { label: "Break", icon: "wagon" },
  Coupe: { label: "Coupe / Sport", icon: "sport" },
  Monospace: { label: "Monospace", icon: "van" },
  Utilitaire: { label: "Utilitaire", icon: "truck" },
}

export const carbonGradeConfig: Record<
  CarbonGrade,
  { label: string; color: string; bgColor: string; borderColor: string; range: string }
> = {
  A: {
    label: "A",
    color: "#166534",
    bgColor: "#dcfce7",
    borderColor: "#22c55e",
    range: "0-50 g/km",
  },
  B: {
    label: "B",
    color: "#15803d",
    bgColor: "#d1fae5",
    borderColor: "#34d399",
    range: "51-100 g/km",
  },
  C: {
    label: "C",
    color: "#a16207",
    bgColor: "#fef9c3",
    borderColor: "#facc15",
    range: "101-120 g/km",
  },
  D: {
    label: "D",
    color: "#b45309",
    bgColor: "#ffedd5",
    borderColor: "#fb923c",
    range: "121-140 g/km",
  },
  E: {
    label: "E",
    color: "#c2410c",
    bgColor: "#fee2e2",
    borderColor: "#f87171",
    range: "141-160 g/km",
  },
  F: {
    label: "F",
    color: "#b91c1c",
    bgColor: "#fecaca",
    borderColor: "#ef4444",
    range: "161-200 g/km",
  },
  G: {
    label: "G",
    color: "#7f1d1d",
    bgColor: "#fca5a5",
    borderColor: "#dc2626",
    range: "200+ g/km",
  },
}

function getGrade(co2: number): CarbonGrade {
  if (co2 <= 50) return "A"
  if (co2 <= 100) return "B"
  if (co2 <= 120) return "C"
  if (co2 <= 140) return "D"
  if (co2 <= 160) return "E"
  if (co2 <= 200) return "F"
  return "G"
}

const rawCars: Omit<Car, "carbonGrade">[] = [
  {
    id: "1",
    brand: "Tesla",
    model: "Model 3",
    year: 2022,
    price: 32900,
    mileage: 28000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "283 ch",
    image: "/images/tesla-model3.jpg",
    location: "Paris (75)",
    category: "Berline",
    doors: 4,
    seats: 5,
    trunkVolume: 425,
    color: "Blanc",
    drivetrain: "Propulsion",
    euroNorm: "Euro 6d",
    autonomy: 491,
    cylinders: "Moteur electrique",
    weight: 1761,
    vin: "5YJ3E1EA8NF384291",
    vinHistory: [
      { date: "03/2022", event: "Premiere immatriculation", mileage: 0, location: "Paris (75)", status: "info" },
      { date: "03/2023", event: "Revision constructeur - RAS", mileage: 15200, location: "Paris (75)", status: "ok" },
      { date: "09/2023", event: "Controle technique - Favorable", mileage: 22100, location: "Paris (75)", status: "ok" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 28000, location: "Paris (75)", status: "ok" },
    ],
  },
  {
    id: "2",
    brand: "Renault",
    model: "Zoe",
    year: 2021,
    price: 18500,
    mileage: 35000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "136 ch",
    image: "/images/renault-zoe.jpg",
    location: "Lyon (69)",
    category: "Citadine",
    doors: 5,
    seats: 5,
    trunkVolume: 338,
    color: "Bleu",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 395,
    cylinders: "Moteur electrique",
    weight: 1502,
    vin: "VF1AG000365217834",
    vinHistory: [
      { date: "06/2021", event: "Premiere immatriculation", mileage: 0, location: "Lyon (69)", status: "info" },
      { date: "06/2022", event: "Revision constructeur - RAS", mileage: 18500, location: "Lyon (69)", status: "ok" },
      { date: "06/2023", event: "Controle technique - Favorable", mileage: 28700, location: "Lyon (69)", status: "ok" },
      { date: "01/2024", event: "Remplacement pneus avant", mileage: 32100, location: "Lyon (69)", status: "info" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 35000, location: "Lyon (69)", status: "ok" },
    ],
  },
  {
    id: "3",
    brand: "Toyota",
    model: "Yaris Hybride",
    year: 2023,
    price: 21900,
    mileage: 12000,
    fuel: "Hybride",
    co2: 92,
    transmission: "Automatique",
    power: "116 ch",
    image: "/images/toyota-yaris.jpg",
    location: "Marseille (13)",
    category: "Citadine",
    doors: 5,
    seats: 5,
    trunkVolume: 286,
    color: "Rouge",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 0,
    cylinders: "1.5L 3 cyl + electrique",
    weight: 1090,
    vin: "JTDKN3DU5P3087641",
    vinHistory: [
      { date: "01/2023", event: "Premiere immatriculation", mileage: 0, location: "Marseille (13)", status: "info" },
      { date: "01/2024", event: "Revision constructeur - RAS", mileage: 12000, location: "Marseille (13)", status: "ok" },
    ],
  },
  {
    id: "4",
    brand: "Peugeot",
    model: "e-208",
    year: 2022,
    price: 24500,
    mileage: 18000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "136 ch",
    image: "/images/peugeot-e208.jpg",
    location: "Bordeaux (33)",
    category: "Citadine",
    doors: 5,
    seats: 5,
    trunkVolume: 311,
    color: "Jaune",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 362,
    cylinders: "Moteur electrique",
    weight: 1455,
    vin: "VR3UHZKXZNJ052489",
    vinHistory: [
      { date: "04/2022", event: "Premiere immatriculation", mileage: 0, location: "Bordeaux (33)", status: "info" },
      { date: "04/2023", event: "Revision constructeur - RAS", mileage: 11200, location: "Bordeaux (33)", status: "ok" },
      { date: "10/2023", event: "Rappel constructeur - Mise a jour logicielle", mileage: 14800, location: "Bordeaux (33)", status: "warning" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 18000, location: "Bordeaux (33)", status: "ok" },
    ],
  },
  {
    id: "5",
    brand: "Hyundai",
    model: "Kona Electric",
    year: 2021,
    price: 27900,
    mileage: 32000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "204 ch",
    image: "/images/hyundai-kona.jpg",
    location: "Toulouse (31)",
    category: "SUV",
    doors: 5,
    seats: 5,
    trunkVolume: 332,
    color: "Blanc",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 484,
    cylinders: "Moteur electrique",
    weight: 1685,
    vin: "KMHK381GDMU093756",
    vinHistory: [
      { date: "09/2021", event: "Premiere immatriculation", mileage: 0, location: "Toulouse (31)", status: "info" },
      { date: "09/2022", event: "Revision constructeur - RAS", mileage: 16000, location: "Toulouse (31)", status: "ok" },
      { date: "09/2023", event: "Controle technique - Favorable", mileage: 26500, location: "Toulouse (31)", status: "ok" },
      { date: "03/2024", event: "Changement batterie 12V", mileage: 30200, location: "Toulouse (31)", status: "info" },
      { date: "09/2024", event: "Revision constructeur - RAS", mileage: 32000, location: "Toulouse (31)", status: "ok" },
    ],
  },
  {
    id: "6",
    brand: "Toyota",
    model: "Corolla Hybride",
    year: 2022,
    price: 25400,
    mileage: 22000,
    fuel: "Hybride",
    co2: 101,
    transmission: "Automatique",
    power: "140 ch",
    image: "/images/toyota-corolla.jpg",
    location: "Nantes (44)",
    category: "Berline",
    doors: 4,
    seats: 5,
    trunkVolume: 361,
    color: "Gris",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 0,
    cylinders: "1.8L 4 cyl + electrique",
    weight: 1365,
    vin: "JTDEBRBE40N214587",
    vinHistory: [
      { date: "05/2022", event: "Premiere immatriculation", mileage: 0, location: "Nantes (44)", status: "info" },
      { date: "05/2023", event: "Revision constructeur - RAS", mileage: 14000, location: "Nantes (44)", status: "ok" },
      { date: "11/2023", event: "Controle technique - Favorable", mileage: 18500, location: "Nantes (44)", status: "ok" },
      { date: "05/2024", event: "Revision constructeur - RAS", mileage: 22000, location: "Nantes (44)", status: "ok" },
    ],
  },
  {
    id: "7",
    brand: "Volkswagen",
    model: "Golf 8",
    year: 2021,
    price: 22800,
    mileage: 45000,
    fuel: "Essence",
    co2: 124,
    transmission: "Manuelle",
    power: "130 ch",
    image: "/images/vw-golf.jpg",
    location: "Strasbourg (67)",
    category: "Berline",
    doors: 5,
    seats: 5,
    trunkVolume: 381,
    color: "Gris",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 0,
    cylinders: "1.5L TSI 4 cyl",
    weight: 1310,
    vin: "WVWZZZCDZMW198432",
    vinHistory: [
      { date: "03/2021", event: "Premiere immatriculation", mileage: 0, location: "Strasbourg (67)", status: "info" },
      { date: "03/2022", event: "Revision constructeur - RAS", mileage: 15000, location: "Strasbourg (67)", status: "ok" },
      { date: "03/2023", event: "Controle technique - Favorable", mileage: 30200, location: "Strasbourg (67)", status: "ok" },
      { date: "08/2023", event: "Accrochage leger - Reparation pare-chocs", mileage: 36100, location: "Strasbourg (67)", status: "warning" },
      { date: "03/2024", event: "Revision constructeur - RAS", mileage: 45000, location: "Strasbourg (67)", status: "ok" },
    ],
  },
  {
    id: "8",
    brand: "Peugeot",
    model: "3008",
    year: 2022,
    price: 29900,
    mileage: 35000,
    fuel: "Diesel",
    co2: 131,
    transmission: "Automatique",
    power: "130 ch",
    image: "/images/peugeot-3008.jpg",
    location: "Lille (59)",
    category: "SUV",
    doors: 5,
    seats: 5,
    trunkVolume: 520,
    color: "Noir",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 0,
    cylinders: "1.5L BlueHDi 4 cyl",
    weight: 1410,
    vin: "VF3MCBHZMNS156723",
    vinHistory: [
      { date: "02/2022", event: "Premiere immatriculation", mileage: 0, location: "Lille (59)", status: "info" },
      { date: "02/2023", event: "Revision constructeur - RAS", mileage: 18000, location: "Lille (59)", status: "ok" },
      { date: "08/2023", event: "Controle technique - Favorable", mileage: 26200, location: "Lille (59)", status: "ok" },
      { date: "02/2024", event: "Revision constructeur - RAS", mileage: 35000, location: "Lille (59)", status: "ok" },
    ],
  },
  {
    id: "9",
    brand: "Renault",
    model: "Megane",
    year: 2020,
    price: 16500,
    mileage: 58000,
    fuel: "Diesel",
    co2: 109,
    transmission: "Manuelle",
    power: "115 ch",
    image: "/images/renault-megane.jpg",
    location: "Nice (06)",
    category: "Berline",
    doors: 5,
    seats: 5,
    trunkVolume: 384,
    color: "Gris",
    drivetrain: "Traction",
    euroNorm: "Euro 6",
    autonomy: 0,
    cylinders: "1.5L dCi 4 cyl",
    weight: 1310,
    vin: "VF1RFB00X64382917",
    vinHistory: [
      { date: "07/2020", event: "Premiere immatriculation", mileage: 0, location: "Nice (06)", status: "info" },
      { date: "07/2021", event: "Revision constructeur - RAS", mileage: 14500, location: "Nice (06)", status: "ok" },
      { date: "07/2022", event: "Controle technique - Favorable", mileage: 30100, location: "Nice (06)", status: "ok" },
      { date: "01/2023", event: "Remplacement plaquettes frein AV", mileage: 38200, location: "Nice (06)", status: "info" },
      { date: "07/2023", event: "Revision constructeur - RAS", mileage: 46000, location: "Nice (06)", status: "ok" },
      { date: "07/2024", event: "Controle technique - Favorable", mileage: 58000, location: "Nice (06)", status: "ok" },
    ],
  },
  {
    id: "10",
    brand: "BMW",
    model: "Serie 3 320d",
    year: 2021,
    price: 34900,
    mileage: 42000,
    fuel: "Diesel",
    co2: 127,
    transmission: "Automatique",
    power: "190 ch",
    image: "/images/bmw-serie3.jpg",
    location: "Montpellier (34)",
    category: "Berline",
    doors: 4,
    seats: 5,
    trunkVolume: 480,
    color: "Bleu",
    drivetrain: "Propulsion",
    euroNorm: "Euro 6d",
    autonomy: 0,
    cylinders: "2.0L 4 cyl turbo",
    weight: 1565,
    vin: "WBA5R1C08MFH73621",
    vinHistory: [
      { date: "04/2021", event: "Premiere immatriculation", mileage: 0, location: "Montpellier (34)", status: "info" },
      { date: "04/2022", event: "Revision constructeur - RAS", mileage: 15000, location: "Montpellier (34)", status: "ok" },
      { date: "10/2022", event: "Controle technique - Favorable", mileage: 22500, location: "Montpellier (34)", status: "ok" },
      { date: "04/2023", event: "Revision constructeur - RAS", mileage: 30000, location: "Montpellier (34)", status: "ok" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 42000, location: "Montpellier (34)", status: "ok" },
    ],
  },
  {
    id: "11",
    brand: "Audi",
    model: "A4 40 TFSI",
    year: 2021,
    price: 36500,
    mileage: 38000,
    fuel: "Essence",
    co2: 152,
    transmission: "Automatique",
    power: "204 ch",
    image: "/images/audi-a4.jpg",
    location: "Rennes (35)",
    category: "Berline",
    doors: 4,
    seats: 5,
    trunkVolume: 460,
    color: "Blanc",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 0,
    cylinders: "2.0L TFSI 4 cyl turbo",
    weight: 1530,
    vin: "WAUZZZF47MA061849",
    vinHistory: [
      { date: "06/2021", event: "Premiere immatriculation", mileage: 0, location: "Rennes (35)", status: "info" },
      { date: "06/2022", event: "Revision constructeur - RAS", mileage: 13000, location: "Rennes (35)", status: "ok" },
      { date: "12/2022", event: "Controle technique - Favorable", mileage: 20100, location: "Rennes (35)", status: "ok" },
      { date: "06/2023", event: "Revision constructeur - RAS", mileage: 27000, location: "Rennes (35)", status: "ok" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 38000, location: "Rennes (35)", status: "ok" },
    ],
  },
  {
    id: "12",
    brand: "Mercedes",
    model: "Classe C 200",
    year: 2020,
    price: 33200,
    mileage: 52000,
    fuel: "Essence",
    co2: 162,
    transmission: "Automatique",
    power: "184 ch",
    image: "/images/mercedes-c200.jpg",
    location: "Grenoble (38)",
    category: "Berline",
    doors: 4,
    seats: 5,
    trunkVolume: 455,
    color: "Gris",
    drivetrain: "Propulsion",
    euroNorm: "Euro 6",
    autonomy: 0,
    cylinders: "1.5L 4 cyl turbo",
    weight: 1500,
    vin: "W1KZF8DB7LR504832",
    vinHistory: [
      { date: "09/2020", event: "Premiere immatriculation", mileage: 0, location: "Grenoble (38)", status: "info" },
      { date: "09/2021", event: "Revision constructeur - RAS", mileage: 16000, location: "Grenoble (38)", status: "ok" },
      { date: "03/2022", event: "Controle technique - Favorable", mileage: 25200, location: "Grenoble (38)", status: "ok" },
      { date: "09/2022", event: "Rappel constructeur - Capteur NOx", mileage: 30100, location: "Grenoble (38)", status: "warning" },
      { date: "09/2023", event: "Revision constructeur - RAS", mileage: 42500, location: "Grenoble (38)", status: "ok" },
      { date: "03/2024", event: "Controle technique - Favorable", mileage: 52000, location: "Grenoble (38)", status: "ok" },
    ],
  },
  {
    id: "13",
    brand: "Ford",
    model: "Mustang GT",
    year: 2020,
    price: 42000,
    mileage: 28000,
    fuel: "Essence",
    co2: 281,
    transmission: "Automatique",
    power: "450 ch",
    image: "/images/ford-mustang.jpg",
    location: "Bordeaux (33)",
    category: "Coupe",
    doors: 2,
    seats: 4,
    trunkVolume: 382,
    color: "Rouge",
    drivetrain: "Propulsion",
    euroNorm: "Euro 6",
    autonomy: 0,
    cylinders: "5.0L V8",
    weight: 1845,
    vin: "1FA6P8CF6L5143987",
    vinHistory: [
      { date: "06/2020", event: "Premiere immatriculation (import US)", mileage: 0, location: "Bordeaux (33)", status: "info" },
      { date: "06/2021", event: "Revision constructeur - RAS", mileage: 10500, location: "Bordeaux (33)", status: "ok" },
      { date: "12/2021", event: "Controle technique - Favorable", mileage: 16200, location: "Bordeaux (33)", status: "ok" },
      { date: "06/2022", event: "Remplacement pneus arriere", mileage: 20000, location: "Bordeaux (33)", status: "info" },
      { date: "06/2023", event: "Revision constructeur - RAS", mileage: 24500, location: "Bordeaux (33)", status: "ok" },
      { date: "12/2023", event: "Controle technique - Favorable", mileage: 28000, location: "Bordeaux (33)", status: "ok" },
    ],
  },
  {
    id: "14",
    brand: "Volkswagen",
    model: "Tiguan 2.0 TDI",
    year: 2021,
    price: 31500,
    mileage: 40000,
    fuel: "Diesel",
    co2: 157,
    transmission: "Automatique",
    power: "150 ch",
    image: "/images/vw-tiguan.jpg",
    location: "Dijon (21)",
    category: "SUV",
    doors: 5,
    seats: 5,
    trunkVolume: 615,
    color: "Blanc",
    drivetrain: "Integrale",
    euroNorm: "Euro 6d",
    autonomy: 0,
    cylinders: "2.0L TDI 4 cyl turbo",
    weight: 1661,
    vin: "WVGZZZCDZM8124567",
    vinHistory: [
      { date: "05/2021", event: "Premiere immatriculation", mileage: 0, location: "Dijon (21)", status: "info" },
      { date: "05/2022", event: "Revision constructeur - RAS", mileage: 14000, location: "Dijon (21)", status: "ok" },
      { date: "11/2022", event: "Controle technique - Favorable", mileage: 22000, location: "Dijon (21)", status: "ok" },
      { date: "05/2023", event: "Revision constructeur - RAS", mileage: 30500, location: "Dijon (21)", status: "ok" },
      { date: "05/2024", event: "Revision constructeur - RAS", mileage: 40000, location: "Dijon (21)", status: "ok" },
    ],
  },
  {
    id: "15",
    brand: "Porsche",
    model: "Cayenne",
    year: 2019,
    price: 55000,
    mileage: 55000,
    fuel: "Essence",
    co2: 230,
    transmission: "Automatique",
    power: "340 ch",
    image: "/images/porsche-cayenne.jpg",
    location: "Paris (75)",
    category: "SUV",
    doors: 5,
    seats: 5,
    trunkVolume: 770,
    color: "Noir",
    drivetrain: "Integrale",
    euroNorm: "Euro 6",
    autonomy: 0,
    cylinders: "3.0L V6 turbo",
    weight: 2040,
    vin: "WP1AA2AY3KDA48215",
    vinHistory: [
      { date: "11/2019", event: "Premiere immatriculation", mileage: 0, location: "Paris (75)", status: "info" },
      { date: "11/2020", event: "Revision constructeur - RAS", mileage: 12000, location: "Paris (75)", status: "ok" },
      { date: "05/2021", event: "Controle technique - Favorable", mileage: 22500, location: "Paris (75)", status: "ok" },
      { date: "11/2021", event: "Revision constructeur - RAS", mileage: 30000, location: "Paris (75)", status: "ok" },
      { date: "06/2022", event: "Sinistre declare - Choc lateral repare", mileage: 37200, location: "Paris (75)", status: "warning" },
      { date: "11/2022", event: "Revision constructeur - RAS", mileage: 42000, location: "Paris (75)", status: "ok" },
      { date: "05/2023", event: "Controle technique - Favorable", mileage: 49500, location: "Paris (75)", status: "ok" },
      { date: "11/2023", event: "Revision constructeur - RAS", mileage: 55000, location: "Paris (75)", status: "ok" },
    ],
  },
  {
    id: "16",
    brand: "Dacia",
    model: "Spring",
    year: 2023,
    price: 14900,
    mileage: 8000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "65 ch",
    image: "/images/dacia-spring.jpg",
    location: "Tours (37)",
    category: "Citadine",
    doors: 5,
    seats: 4,
    trunkVolume: 290,
    color: "Vert",
    drivetrain: "Traction",
    euroNorm: "Euro 6d",
    autonomy: 230,
    cylinders: "Moteur electrique",
    weight: 1042,
    vin: "UU1DKFEE1P1237845",
    vinHistory: [
      { date: "02/2023", event: "Premiere immatriculation", mileage: 0, location: "Tours (37)", status: "info" },
      { date: "02/2024", event: "Revision constructeur - RAS", mileage: 8000, location: "Tours (37)", status: "ok" },
    ],
  },
  // --- 40 NEW VEHICLES ---
  {
    id: "17",
    brand: "Citroen",
    model: "C3",
    year: 2022,
    price: 14200,
    mileage: 25000,
    fuel: "Essence",
    co2: 117,
    transmission: "Manuelle",
    power: "83 ch",
    image: "/images/citroen-c3.jpg",
    location: "Paris (75)",
    category: "Citadine",
    doors: 5, seats: 5, trunkVolume: 300, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.2L 3 cyl", weight: 1050,
    vin: "VF7SXHMZ6NT512348",
    vinHistory: [
      { date: "03/2022", event: "Premiere immatriculation", mileage: 0, location: "Paris (75)", status: "info" },
      { date: "03/2023", event: "Revision constructeur - RAS", mileage: 14000, location: "Paris (75)", status: "ok" },
      { date: "03/2024", event: "Controle technique - Favorable", mileage: 25000, location: "Paris (75)", status: "ok" },
    ],
  },
  {
    id: "18",
    brand: "Fiat",
    model: "500e",
    year: 2023,
    price: 22900,
    mileage: 9000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "118 ch",
    image: "/images/fiat-500e.jpg",
    location: "Nice (06)",
    category: "Citadine",
    doors: 3, seats: 4, trunkVolume: 185, color: "Vert", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 320, cylinders: "Moteur electrique", weight: 1365,
    vin: "ZFAEF1CL5P3098712",
    vinHistory: [
      { date: "05/2023", event: "Premiere immatriculation", mileage: 0, location: "Nice (06)", status: "info" },
      { date: "05/2024", event: "Revision constructeur - RAS", mileage: 9000, location: "Nice (06)", status: "ok" },
    ],
  },
  {
    id: "19",
    brand: "Skoda",
    model: "Octavia Combi",
    year: 2021,
    price: 23500,
    mileage: 52000,
    fuel: "Diesel",
    co2: 116,
    transmission: "Automatique",
    power: "150 ch",
    image: "/images/skoda-octavia.jpg",
    location: "Strasbourg (67)",
    category: "Break",
    doors: 5, seats: 5, trunkVolume: 640, color: "Gris", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.0L TDI 4 cyl", weight: 1455,
    vin: "TMBAJ7NP6M0156234",
    vinHistory: [
      { date: "06/2021", event: "Premiere immatriculation", mileage: 0, location: "Strasbourg (67)", status: "info" },
      { date: "06/2022", event: "Revision constructeur - RAS", mileage: 22000, location: "Strasbourg (67)", status: "ok" },
      { date: "06/2023", event: "Controle technique - Favorable", mileage: 40000, location: "Strasbourg (67)", status: "ok" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 52000, location: "Strasbourg (67)", status: "ok" },
    ],
  },
  {
    id: "20",
    brand: "Kia",
    model: "EV6",
    year: 2023,
    price: 39900,
    mileage: 15000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "229 ch",
    image: "/images/kia-ev6.jpg",
    location: "Lyon (69)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 490, color: "Gris", drivetrain: "Propulsion",
    euroNorm: "Euro 6d", autonomy: 528, cylinders: "Moteur electrique", weight: 1930,
    vin: "KNAE351ADPA098321",
    vinHistory: [
      { date: "02/2023", event: "Premiere immatriculation", mileage: 0, location: "Lyon (69)", status: "info" },
      { date: "02/2024", event: "Revision constructeur - RAS", mileage: 15000, location: "Lyon (69)", status: "ok" },
    ],
  },
  {
    id: "21",
    brand: "Seat",
    model: "Leon 1.5 TSI",
    year: 2022,
    price: 20800,
    mileage: 30000,
    fuel: "Essence",
    co2: 126,
    transmission: "Manuelle",
    power: "130 ch",
    image: "/images/seat-leon.jpg",
    location: "Toulouse (31)",
    category: "Berline",
    doors: 5, seats: 5, trunkVolume: 380, color: "Rouge", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.5L TSI 4 cyl", weight: 1290,
    vin: "VSSZZZKL6NR054721",
    vinHistory: [
      { date: "04/2022", event: "Premiere immatriculation", mileage: 0, location: "Toulouse (31)", status: "info" },
      { date: "04/2023", event: "Revision constructeur - RAS", mileage: 16000, location: "Toulouse (31)", status: "ok" },
      { date: "04/2024", event: "Controle technique - Favorable", mileage: 30000, location: "Toulouse (31)", status: "ok" },
    ],
  },
  {
    id: "22",
    brand: "Volvo",
    model: "XC40 Recharge",
    year: 2022,
    price: 38500,
    mileage: 20000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "231 ch",
    image: "/images/volvo-xc40.jpg",
    location: "Rennes (35)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 419, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 425, cylinders: "Moteur electrique", weight: 2030,
    vin: "YV1XZ89RDN2187654",
    vinHistory: [
      { date: "07/2022", event: "Premiere immatriculation", mileage: 0, location: "Rennes (35)", status: "info" },
      { date: "07/2023", event: "Revision constructeur - RAS", mileage: 12000, location: "Rennes (35)", status: "ok" },
      { date: "07/2024", event: "Revision constructeur - RAS", mileage: 20000, location: "Rennes (35)", status: "ok" },
    ],
  },
  {
    id: "23",
    brand: "Opel",
    model: "Corsa-e",
    year: 2022,
    price: 21900,
    mileage: 22000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "136 ch",
    image: "/images/opel-corsa-e.jpg",
    location: "Lille (59)",
    category: "Citadine",
    doors: 5, seats: 5, trunkVolume: 267, color: "Jaune", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 353, cylinders: "Moteur electrique", weight: 1530,
    vin: "W0L000008N4021345",
    vinHistory: [
      { date: "05/2022", event: "Premiere immatriculation", mileage: 0, location: "Lille (59)", status: "info" },
      { date: "05/2023", event: "Revision constructeur - RAS", mileage: 12000, location: "Lille (59)", status: "ok" },
      { date: "05/2024", event: "Controle technique - Favorable", mileage: 22000, location: "Lille (59)", status: "ok" },
    ],
  },
  {
    id: "24",
    brand: "Mini",
    model: "Cooper S",
    year: 2021,
    price: 25500,
    mileage: 35000,
    fuel: "Essence",
    co2: 153,
    transmission: "Automatique",
    power: "178 ch",
    image: "/images/mini-cooper.jpg",
    location: "Paris (75)",
    category: "Citadine",
    doors: 3, seats: 4, trunkVolume: 211, color: "Vert", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.0L 4 cyl turbo", weight: 1250,
    vin: "WMWXU9C05M2K87431",
    vinHistory: [
      { date: "09/2021", event: "Premiere immatriculation", mileage: 0, location: "Paris (75)", status: "info" },
      { date: "09/2022", event: "Revision constructeur - RAS", mileage: 18000, location: "Paris (75)", status: "ok" },
      { date: "03/2023", event: "Controle technique - Favorable", mileage: 24000, location: "Paris (75)", status: "ok" },
      { date: "09/2023", event: "Revision constructeur - RAS", mileage: 35000, location: "Paris (75)", status: "ok" },
    ],
  },
  {
    id: "25",
    brand: "Nissan",
    model: "Leaf e+",
    year: 2021,
    price: 20500,
    mileage: 40000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "217 ch",
    image: "/images/nissan-leaf.jpg",
    location: "Nantes (44)",
    category: "Berline",
    doors: 5, seats: 5, trunkVolume: 435, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 385, cylinders: "Moteur electrique", weight: 1640,
    vin: "SJNFAAZE1U0312876",
    vinHistory: [
      { date: "03/2021", event: "Premiere immatriculation", mileage: 0, location: "Nantes (44)", status: "info" },
      { date: "03/2022", event: "Revision constructeur - RAS", mileage: 15000, location: "Nantes (44)", status: "ok" },
      { date: "09/2022", event: "Controle technique - Favorable", mileage: 25000, location: "Nantes (44)", status: "ok" },
      { date: "03/2023", event: "Revision constructeur - RAS", mileage: 32000, location: "Nantes (44)", status: "ok" },
      { date: "03/2024", event: "Revision constructeur - RAS", mileage: 40000, location: "Nantes (44)", status: "ok" },
    ],
  },
  {
    id: "26",
    brand: "Mazda",
    model: "CX-5 2.2 Skyactiv-D",
    year: 2021,
    price: 28900,
    mileage: 48000,
    fuel: "Diesel",
    co2: 152,
    transmission: "Automatique",
    power: "184 ch",
    image: "/images/mazda-cx5.jpg",
    location: "Grenoble (38)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 506, color: "Rouge", drivetrain: "Integrale",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.2L 4 cyl turbo", weight: 1655,
    vin: "JMZKE2CY6M0198432",
    vinHistory: [
      { date: "02/2021", event: "Premiere immatriculation", mileage: 0, location: "Grenoble (38)", status: "info" },
      { date: "02/2022", event: "Revision constructeur - RAS", mileage: 18000, location: "Grenoble (38)", status: "ok" },
      { date: "08/2022", event: "Controle technique - Favorable", mileage: 28000, location: "Grenoble (38)", status: "ok" },
      { date: "02/2023", event: "Revision constructeur - RAS", mileage: 36000, location: "Grenoble (38)", status: "ok" },
      { date: "02/2024", event: "Revision constructeur - RAS", mileage: 48000, location: "Grenoble (38)", status: "ok" },
    ],
  },
  {
    id: "27",
    brand: "Renault",
    model: "Captur E-Tech Hybride",
    year: 2023,
    price: 26800,
    mileage: 14000,
    fuel: "Hybride",
    co2: 105,
    transmission: "Automatique",
    power: "145 ch",
    image: "/images/renault-zoe.jpg",
    location: "Marseille (13)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 440, color: "Orange", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.6L 4 cyl + electrique", weight: 1420,
    vin: "VF1RJA00870543219",
    vinHistory: [
      { date: "01/2023", event: "Premiere immatriculation", mileage: 0, location: "Marseille (13)", status: "info" },
      { date: "01/2024", event: "Revision constructeur - RAS", mileage: 14000, location: "Marseille (13)", status: "ok" },
    ],
  },
  {
    id: "28",
    brand: "Peugeot",
    model: "508 SW",
    year: 2021,
    price: 27800,
    mileage: 55000,
    fuel: "Diesel",
    co2: 115,
    transmission: "Automatique",
    power: "130 ch",
    image: "/images/peugeot-3008.jpg",
    location: "Bordeaux (33)",
    category: "Break",
    doors: 5, seats: 5, trunkVolume: 530, color: "Noir", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.5L BlueHDi 4 cyl", weight: 1490,
    vin: "VF3LCYHZMMS098712",
    vinHistory: [
      { date: "04/2021", event: "Premiere immatriculation", mileage: 0, location: "Bordeaux (33)", status: "info" },
      { date: "04/2022", event: "Revision constructeur - RAS", mileage: 20000, location: "Bordeaux (33)", status: "ok" },
      { date: "10/2022", event: "Controle technique - Favorable", mileage: 32000, location: "Bordeaux (33)", status: "ok" },
      { date: "04/2023", event: "Revision constructeur - RAS", mileage: 42000, location: "Bordeaux (33)", status: "ok" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 55000, location: "Bordeaux (33)", status: "ok" },
    ],
  },
  {
    id: "29",
    brand: "Toyota",
    model: "RAV4 Hybride",
    year: 2022,
    price: 36200,
    mileage: 28000,
    fuel: "Hybride",
    co2: 120,
    transmission: "Automatique",
    power: "218 ch",
    image: "/images/toyota-corolla.jpg",
    location: "Montpellier (34)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 580, color: "Blanc", drivetrain: "Integrale",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.5L 4 cyl + electrique", weight: 1680,
    vin: "JTMW1RFV5ND098543",
    vinHistory: [
      { date: "06/2022", event: "Premiere immatriculation", mileage: 0, location: "Montpellier (34)", status: "info" },
      { date: "06/2023", event: "Revision constructeur - RAS", mileage: 15000, location: "Montpellier (34)", status: "ok" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 28000, location: "Montpellier (34)", status: "ok" },
    ],
  },
  {
    id: "30",
    brand: "BMW",
    model: "X1 xDrive25e",
    year: 2022,
    price: 37900,
    mileage: 30000,
    fuel: "Hybride",
    co2: 28,
    transmission: "Automatique",
    power: "245 ch",
    image: "/images/bmw-serie3.jpg",
    location: "Lyon (69)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 450, color: "Blanc", drivetrain: "Integrale",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.5L 3 cyl turbo + electrique", weight: 1845,
    vin: "WBAUN110XM7E98321",
    vinHistory: [
      { date: "03/2022", event: "Premiere immatriculation", mileage: 0, location: "Lyon (69)", status: "info" },
      { date: "03/2023", event: "Revision constructeur - RAS", mileage: 16000, location: "Lyon (69)", status: "ok" },
      { date: "09/2023", event: "Controle technique - Favorable", mileage: 22000, location: "Lyon (69)", status: "ok" },
      { date: "03/2024", event: "Revision constructeur - RAS", mileage: 30000, location: "Lyon (69)", status: "ok" },
    ],
  },
  {
    id: "31",
    brand: "Ford",
    model: "Puma 1.0 EcoBoost",
    year: 2022,
    price: 21500,
    mileage: 28000,
    fuel: "Essence",
    co2: 130,
    transmission: "Manuelle",
    power: "125 ch",
    image: "/images/ford-mustang.jpg",
    location: "Dijon (21)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 456, color: "Bleu", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.0L 3 cyl turbo", weight: 1250,
    vin: "WF0JXXGCDJMY21345",
    vinHistory: [
      { date: "05/2022", event: "Premiere immatriculation", mileage: 0, location: "Dijon (21)", status: "info" },
      { date: "05/2023", event: "Revision constructeur - RAS", mileage: 15000, location: "Dijon (21)", status: "ok" },
      { date: "05/2024", event: "Controle technique - Favorable", mileage: 28000, location: "Dijon (21)", status: "ok" },
    ],
  },
  {
    id: "32",
    brand: "Mercedes",
    model: "EQA 250",
    year: 2022,
    price: 38900,
    mileage: 18000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "190 ch",
    image: "/images/mercedes-c200.jpg",
    location: "Paris (75)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 340, color: "Gris", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 426, cylinders: "Moteur electrique", weight: 2040,
    vin: "W1N2430121W098765",
    vinHistory: [
      { date: "06/2022", event: "Premiere immatriculation", mileage: 0, location: "Paris (75)", status: "info" },
      { date: "06/2023", event: "Revision constructeur - RAS", mileage: 10000, location: "Paris (75)", status: "ok" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 18000, location: "Paris (75)", status: "ok" },
    ],
  },
  {
    id: "33",
    brand: "Audi",
    model: "Q3 35 TFSI",
    year: 2022,
    price: 33500,
    mileage: 26000,
    fuel: "Essence",
    co2: 156,
    transmission: "Automatique",
    power: "150 ch",
    image: "/images/audi-a4.jpg",
    location: "Toulouse (31)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 530, color: "Noir", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.5L TFSI 4 cyl turbo", weight: 1530,
    vin: "WAUZZZ8V6NA032187",
    vinHistory: [
      { date: "02/2022", event: "Premiere immatriculation", mileage: 0, location: "Toulouse (31)", status: "info" },
      { date: "02/2023", event: "Revision constructeur - RAS", mileage: 14000, location: "Toulouse (31)", status: "ok" },
      { date: "08/2023", event: "Controle technique - Favorable", mileage: 20000, location: "Toulouse (31)", status: "ok" },
      { date: "02/2024", event: "Revision constructeur - RAS", mileage: 26000, location: "Toulouse (31)", status: "ok" },
    ],
  },
  {
    id: "34",
    brand: "Citroen",
    model: "C5 Aircross Hybrid",
    year: 2022,
    price: 30200,
    mileage: 32000,
    fuel: "Hybride",
    co2: 32,
    transmission: "Automatique",
    power: "225 ch",
    image: "/images/citroen-c3.jpg",
    location: "Nantes (44)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 460, color: "Gris", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.6L 4 cyl turbo + electrique", weight: 1780,
    vin: "VF73E5HZ6NS098234",
    vinHistory: [
      { date: "01/2022", event: "Premiere immatriculation", mileage: 0, location: "Nantes (44)", status: "info" },
      { date: "01/2023", event: "Revision constructeur - RAS", mileage: 16000, location: "Nantes (44)", status: "ok" },
      { date: "07/2023", event: "Controle technique - Favorable", mileage: 24000, location: "Nantes (44)", status: "ok" },
      { date: "01/2024", event: "Revision constructeur - RAS", mileage: 32000, location: "Nantes (44)", status: "ok" },
    ],
  },
  {
    id: "35",
    brand: "Volkswagen",
    model: "ID.3 Pro",
    year: 2023,
    price: 29900,
    mileage: 12000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "204 ch",
    image: "/images/vw-golf.jpg",
    location: "Strasbourg (67)",
    category: "Berline",
    doors: 5, seats: 5, trunkVolume: 385, color: "Bleu", drivetrain: "Propulsion",
    euroNorm: "Euro 6d", autonomy: 425, cylinders: "Moteur electrique", weight: 1805,
    vin: "WVWZZZE1ZNP065432",
    vinHistory: [
      { date: "04/2023", event: "Premiere immatriculation", mileage: 0, location: "Strasbourg (67)", status: "info" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 12000, location: "Strasbourg (67)", status: "ok" },
    ],
  },
  {
    id: "36",
    brand: "Dacia",
    model: "Duster 1.5 dCi",
    year: 2022,
    price: 17900,
    mileage: 38000,
    fuel: "Diesel",
    co2: 139,
    transmission: "Manuelle",
    power: "115 ch",
    image: "/images/dacia-spring.jpg",
    location: "Tours (37)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 478, color: "Vert", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.5L dCi 4 cyl", weight: 1360,
    vin: "UU1HSD200N0765432",
    vinHistory: [
      { date: "06/2022", event: "Premiere immatriculation", mileage: 0, location: "Tours (37)", status: "info" },
      { date: "06/2023", event: "Revision constructeur - RAS", mileage: 20000, location: "Tours (37)", status: "ok" },
      { date: "06/2024", event: "Controle technique - Favorable", mileage: 38000, location: "Tours (37)", status: "ok" },
    ],
  },
  {
    id: "37",
    brand: "Hyundai",
    model: "Tucson Hybride",
    year: 2022,
    price: 32500,
    mileage: 25000,
    fuel: "Hybride",
    co2: 135,
    transmission: "Automatique",
    power: "230 ch",
    image: "/images/hyundai-kona.jpg",
    location: "Lille (59)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 546, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.6L 4 cyl turbo + electrique", weight: 1590,
    vin: "KMHJ381CDNU054312",
    vinHistory: [
      { date: "07/2022", event: "Premiere immatriculation", mileage: 0, location: "Lille (59)", status: "info" },
      { date: "07/2023", event: "Revision constructeur - RAS", mileage: 14000, location: "Lille (59)", status: "ok" },
      { date: "07/2024", event: "Revision constructeur - RAS", mileage: 25000, location: "Lille (59)", status: "ok" },
    ],
  },
  {
    id: "38",
    brand: "Toyota",
    model: "C-HR Hybride",
    year: 2023,
    price: 29400,
    mileage: 10000,
    fuel: "Hybride",
    co2: 108,
    transmission: "Automatique",
    power: "184 ch",
    image: "/images/toyota-yaris.jpg",
    location: "Marseille (13)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 310, color: "Noir", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.0L 4 cyl + electrique", weight: 1430,
    vin: "JTDAA4FU0P3021456",
    vinHistory: [
      { date: "03/2023", event: "Premiere immatriculation", mileage: 0, location: "Marseille (13)", status: "info" },
      { date: "03/2024", event: "Revision constructeur - RAS", mileage: 10000, location: "Marseille (13)", status: "ok" },
    ],
  },
  {
    id: "39",
    brand: "Renault",
    model: "Megane E-Tech",
    year: 2023,
    price: 33500,
    mileage: 11000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "220 ch",
    image: "/images/renault-megane.jpg",
    location: "Lyon (69)",
    category: "Berline",
    doors: 5, seats: 5, trunkVolume: 440, color: "Bleu", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 470, cylinders: "Moteur electrique", weight: 1636,
    vin: "VF1RJE00870098543",
    vinHistory: [
      { date: "05/2023", event: "Premiere immatriculation", mileage: 0, location: "Lyon (69)", status: "info" },
      { date: "05/2024", event: "Revision constructeur - RAS", mileage: 11000, location: "Lyon (69)", status: "ok" },
    ],
  },
  {
    id: "40",
    brand: "Peugeot",
    model: "2008",
    year: 2021,
    price: 19500,
    mileage: 42000,
    fuel: "Essence",
    co2: 132,
    transmission: "Manuelle",
    power: "130 ch",
    image: "/images/peugeot-e208.jpg",
    location: "Nice (06)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 434, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.2L PureTech 3 cyl turbo", weight: 1230,
    vin: "VF3P2HMPZMS076543",
    vinHistory: [
      { date: "08/2021", event: "Premiere immatriculation", mileage: 0, location: "Nice (06)", status: "info" },
      { date: "08/2022", event: "Revision constructeur - RAS", mileage: 16000, location: "Nice (06)", status: "ok" },
      { date: "02/2023", event: "Controle technique - Favorable", mileage: 28000, location: "Nice (06)", status: "ok" },
      { date: "08/2023", event: "Revision constructeur - RAS", mileage: 35000, location: "Nice (06)", status: "ok" },
      { date: "08/2024", event: "Revision constructeur - RAS", mileage: 42000, location: "Nice (06)", status: "ok" },
    ],
  },
  {
    id: "41",
    brand: "BMW",
    model: "iX3",
    year: 2022,
    price: 45000,
    mileage: 22000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "286 ch",
    image: "/images/bmw-serie3.jpg",
    location: "Paris (75)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 510, color: "Noir", drivetrain: "Propulsion",
    euroNorm: "Euro 6d", autonomy: 460, cylinders: "Moteur electrique", weight: 2185,
    vin: "WBAUN7105M7A56789",
    vinHistory: [
      { date: "04/2022", event: "Premiere immatriculation", mileage: 0, location: "Paris (75)", status: "info" },
      { date: "04/2023", event: "Revision constructeur - RAS", mileage: 12000, location: "Paris (75)", status: "ok" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 22000, location: "Paris (75)", status: "ok" },
    ],
  },
  {
    id: "42",
    brand: "Skoda",
    model: "Kamiq 1.0 TSI",
    year: 2022,
    price: 19800,
    mileage: 30000,
    fuel: "Essence",
    co2: 127,
    transmission: "Manuelle",
    power: "110 ch",
    image: "/images/skoda-octavia.jpg",
    location: "Grenoble (38)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 400, color: "Gris", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.0L TSI 3 cyl turbo", weight: 1225,
    vin: "TMBAK7NS3N0087654",
    vinHistory: [
      { date: "03/2022", event: "Premiere immatriculation", mileage: 0, location: "Grenoble (38)", status: "info" },
      { date: "03/2023", event: "Revision constructeur - RAS", mileage: 16000, location: "Grenoble (38)", status: "ok" },
      { date: "03/2024", event: "Controle technique - Favorable", mileage: 30000, location: "Grenoble (38)", status: "ok" },
    ],
  },
  {
    id: "43",
    brand: "Kia",
    model: "Sportage Hybride",
    year: 2023,
    price: 34900,
    mileage: 16000,
    fuel: "Hybride",
    co2: 132,
    transmission: "Automatique",
    power: "230 ch",
    image: "/images/kia-ev6.jpg",
    location: "Bordeaux (33)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 587, color: "Vert", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.6L 4 cyl turbo + electrique", weight: 1630,
    vin: "KNAP381CDN5043218",
    vinHistory: [
      { date: "02/2023", event: "Premiere immatriculation", mileage: 0, location: "Bordeaux (33)", status: "info" },
      { date: "02/2024", event: "Revision constructeur - RAS", mileage: 16000, location: "Bordeaux (33)", status: "ok" },
    ],
  },
  {
    id: "44",
    brand: "Seat",
    model: "Ateca 2.0 TDI",
    year: 2021,
    price: 25900,
    mileage: 46000,
    fuel: "Diesel",
    co2: 142,
    transmission: "Automatique",
    power: "150 ch",
    image: "/images/seat-leon.jpg",
    location: "Montpellier (34)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 510, color: "Bleu", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.0L TDI 4 cyl", weight: 1485,
    vin: "VSSZZZKL6MR032198",
    vinHistory: [
      { date: "06/2021", event: "Premiere immatriculation", mileage: 0, location: "Montpellier (34)", status: "info" },
      { date: "06/2022", event: "Revision constructeur - RAS", mileage: 18000, location: "Montpellier (34)", status: "ok" },
      { date: "12/2022", event: "Controle technique - Favorable", mileage: 28000, location: "Montpellier (34)", status: "ok" },
      { date: "06/2023", event: "Revision constructeur - RAS", mileage: 36000, location: "Montpellier (34)", status: "ok" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 46000, location: "Montpellier (34)", status: "ok" },
    ],
  },
  {
    id: "45",
    brand: "Volvo",
    model: "V60 T6 Recharge",
    year: 2022,
    price: 42800,
    mileage: 22000,
    fuel: "Hybride",
    co2: 30,
    transmission: "Automatique",
    power: "340 ch",
    image: "/images/volvo-xc40.jpg",
    location: "Rennes (35)",
    category: "Break",
    doors: 5, seats: 5, trunkVolume: 519, color: "Noir", drivetrain: "Integrale",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.0L 4 cyl turbo + electrique", weight: 2030,
    vin: "YV1FW89AHN2098765",
    vinHistory: [
      { date: "03/2022", event: "Premiere immatriculation", mileage: 0, location: "Rennes (35)", status: "info" },
      { date: "03/2023", event: "Revision constructeur - RAS", mileage: 12000, location: "Rennes (35)", status: "ok" },
      { date: "09/2023", event: "Controle technique - Favorable", mileage: 17000, location: "Rennes (35)", status: "ok" },
      { date: "03/2024", event: "Revision constructeur - RAS", mileage: 22000, location: "Rennes (35)", status: "ok" },
    ],
  },
  {
    id: "46",
    brand: "Opel",
    model: "Mokka-e",
    year: 2022,
    price: 28500,
    mileage: 19000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "136 ch",
    image: "/images/opel-corsa-e.jpg",
    location: "Dijon (21)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 310, color: "Noir", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 338, cylinders: "Moteur electrique", weight: 1598,
    vin: "W0L00000XN4067891",
    vinHistory: [
      { date: "08/2022", event: "Premiere immatriculation", mileage: 0, location: "Dijon (21)", status: "info" },
      { date: "08/2023", event: "Revision constructeur - RAS", mileage: 11000, location: "Dijon (21)", status: "ok" },
      { date: "08/2024", event: "Revision constructeur - RAS", mileage: 19000, location: "Dijon (21)", status: "ok" },
    ],
  },
  {
    id: "47",
    brand: "Nissan",
    model: "Qashqai 1.3 DIG-T",
    year: 2022,
    price: 26500,
    mileage: 34000,
    fuel: "Essence",
    co2: 143,
    transmission: "Automatique",
    power: "158 ch",
    image: "/images/nissan-leaf.jpg",
    location: "Tours (37)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 504, color: "Gris", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.3L 4 cyl turbo", weight: 1430,
    vin: "SJNFAAJ11U0234567",
    vinHistory: [
      { date: "04/2022", event: "Premiere immatriculation", mileage: 0, location: "Tours (37)", status: "info" },
      { date: "04/2023", event: "Revision constructeur - RAS", mileage: 18000, location: "Tours (37)", status: "ok" },
      { date: "10/2023", event: "Controle technique - Favorable", mileage: 26000, location: "Tours (37)", status: "ok" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 34000, location: "Tours (37)", status: "ok" },
    ],
  },
  {
    id: "48",
    brand: "Mazda",
    model: "3 Skyactiv-G",
    year: 2021,
    price: 22200,
    mileage: 35000,
    fuel: "Essence",
    co2: 139,
    transmission: "Manuelle",
    power: "150 ch",
    image: "/images/mazda-cx5.jpg",
    location: "Strasbourg (67)",
    category: "Berline",
    doors: 5, seats: 5, trunkVolume: 351, color: "Rouge", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.0L 4 cyl Skyactiv", weight: 1360,
    vin: "JMZBP3AE5M0176543",
    vinHistory: [
      { date: "05/2021", event: "Premiere immatriculation", mileage: 0, location: "Strasbourg (67)", status: "info" },
      { date: "05/2022", event: "Revision constructeur - RAS", mileage: 14000, location: "Strasbourg (67)", status: "ok" },
      { date: "11/2022", event: "Controle technique - Favorable", mileage: 22000, location: "Strasbourg (67)", status: "ok" },
      { date: "05/2023", event: "Revision constructeur - RAS", mileage: 28000, location: "Strasbourg (67)", status: "ok" },
      { date: "05/2024", event: "Revision constructeur - RAS", mileage: 35000, location: "Strasbourg (67)", status: "ok" },
    ],
  },
  {
    id: "49",
    brand: "Citroen",
    model: "e-C4",
    year: 2023,
    price: 27500,
    mileage: 14000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "136 ch",
    image: "/images/citroen-c3.jpg",
    location: "Lille (59)",
    category: "Berline",
    doors: 5, seats: 5, trunkVolume: 380, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 354, cylinders: "Moteur electrique", weight: 1611,
    vin: "VF7SXNHP6PT098321",
    vinHistory: [
      { date: "01/2023", event: "Premiere immatriculation", mileage: 0, location: "Lille (59)", status: "info" },
      { date: "01/2024", event: "Revision constructeur - RAS", mileage: 14000, location: "Lille (59)", status: "ok" },
    ],
  },
  {
    id: "50",
    brand: "Audi",
    model: "e-tron 50",
    year: 2022,
    price: 48500,
    mileage: 28000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "313 ch",
    image: "/images/audi-a4.jpg",
    location: "Toulouse (31)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 660, color: "Gris", drivetrain: "Integrale",
    euroNorm: "Euro 6d", autonomy: 341, cylinders: "Moteur electrique", weight: 2520,
    vin: "WAUZZZ8V6NA098456",
    vinHistory: [
      { date: "05/2022", event: "Premiere immatriculation", mileage: 0, location: "Toulouse (31)", status: "info" },
      { date: "05/2023", event: "Revision constructeur - RAS", mileage: 15000, location: "Toulouse (31)", status: "ok" },
      { date: "11/2023", event: "Controle technique - Favorable", mileage: 22000, location: "Toulouse (31)", status: "ok" },
      { date: "05/2024", event: "Revision constructeur - RAS", mileage: 28000, location: "Toulouse (31)", status: "ok" },
    ],
  },
  {
    id: "51",
    brand: "Renault",
    model: "Clio 5",
    year: 2022,
    price: 15500,
    mileage: 32000,
    fuel: "Essence",
    co2: 119,
    transmission: "Manuelle",
    power: "100 ch",
    image: "/images/renault-zoe.jpg",
    location: "Marseille (13)",
    category: "Citadine",
    doors: 5, seats: 5, trunkVolume: 391, color: "Rouge", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.0L TCe 3 cyl turbo", weight: 1095,
    vin: "VF1RJA00X70123987",
    vinHistory: [
      { date: "02/2022", event: "Premiere immatriculation", mileage: 0, location: "Marseille (13)", status: "info" },
      { date: "02/2023", event: "Revision constructeur - RAS", mileage: 16000, location: "Marseille (13)", status: "ok" },
      { date: "02/2024", event: "Controle technique - Favorable", mileage: 32000, location: "Marseille (13)", status: "ok" },
    ],
  },
  {
    id: "52",
    brand: "Peugeot",
    model: "308 SW",
    year: 2022,
    price: 26200,
    mileage: 36000,
    fuel: "Diesel",
    co2: 107,
    transmission: "Automatique",
    power: "130 ch",
    image: "/images/peugeot-e208.jpg",
    location: "Montpellier (34)",
    category: "Break",
    doors: 5, seats: 5, trunkVolume: 608, color: "Bleu", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.5L BlueHDi 4 cyl", weight: 1380,
    vin: "VF3P5LCRXNS054321",
    vinHistory: [
      { date: "04/2022", event: "Premiere immatriculation", mileage: 0, location: "Montpellier (34)", status: "info" },
      { date: "04/2023", event: "Revision constructeur - RAS", mileage: 18000, location: "Montpellier (34)", status: "ok" },
      { date: "10/2023", event: "Controle technique - Favorable", mileage: 27000, location: "Montpellier (34)", status: "ok" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 36000, location: "Montpellier (34)", status: "ok" },
    ],
  },
  {
    id: "53",
    brand: "Ford",
    model: "Kuga Hybride",
    year: 2022,
    price: 31200,
    mileage: 28000,
    fuel: "Hybride",
    co2: 26,
    transmission: "Automatique",
    power: "225 ch",
    image: "/images/ford-mustang.jpg",
    location: "Lyon (69)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 405, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "2.5L 4 cyl + electrique", weight: 1844,
    vin: "WF0KXXWPGKMY87654",
    vinHistory: [
      { date: "03/2022", event: "Premiere immatriculation", mileage: 0, location: "Lyon (69)", status: "info" },
      { date: "03/2023", event: "Revision constructeur - RAS", mileage: 15000, location: "Lyon (69)", status: "ok" },
      { date: "09/2023", event: "Controle technique - Favorable", mileage: 22000, location: "Lyon (69)", status: "ok" },
      { date: "03/2024", event: "Revision constructeur - RAS", mileage: 28000, location: "Lyon (69)", status: "ok" },
    ],
  },
  {
    id: "54",
    brand: "Mercedes",
    model: "GLA 200",
    year: 2021,
    price: 33800,
    mileage: 38000,
    fuel: "Essence",
    co2: 158,
    transmission: "Automatique",
    power: "163 ch",
    image: "/images/mercedes-c200.jpg",
    location: "Grenoble (38)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 435, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 0, cylinders: "1.3L 4 cyl turbo", weight: 1510,
    vin: "W1N2470311W056432",
    vinHistory: [
      { date: "09/2021", event: "Premiere immatriculation", mileage: 0, location: "Grenoble (38)", status: "info" },
      { date: "09/2022", event: "Revision constructeur - RAS", mileage: 14000, location: "Grenoble (38)", status: "ok" },
      { date: "03/2023", event: "Controle technique - Favorable", mileage: 22000, location: "Grenoble (38)", status: "ok" },
      { date: "09/2023", event: "Revision constructeur - RAS", mileage: 30000, location: "Grenoble (38)", status: "ok" },
      { date: "09/2024", event: "Revision constructeur - RAS", mileage: 38000, location: "Grenoble (38)", status: "ok" },
    ],
  },
  {
    id: "55",
    brand: "Mini",
    model: "Cooper SE",
    year: 2022,
    price: 27900,
    mileage: 18000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "184 ch",
    image: "/images/mini-cooper.jpg",
    location: "Paris (75)",
    category: "Citadine",
    doors: 3, seats: 4, trunkVolume: 211, color: "Blanc", drivetrain: "Traction",
    euroNorm: "Euro 6d", autonomy: 234, cylinders: "Moteur electrique", weight: 1440,
    vin: "WMWXU9C07N2K34578",
    vinHistory: [
      { date: "06/2022", event: "Premiere immatriculation", mileage: 0, location: "Paris (75)", status: "info" },
      { date: "06/2023", event: "Revision constructeur - RAS", mileage: 10000, location: "Paris (75)", status: "ok" },
      { date: "06/2024", event: "Revision constructeur - RAS", mileage: 18000, location: "Paris (75)", status: "ok" },
    ],
  },
  {
    id: "56",
    brand: "Tesla",
    model: "Model Y",
    year: 2023,
    price: 42500,
    mileage: 12000,
    fuel: "Electrique",
    co2: 0,
    transmission: "Automatique",
    power: "299 ch",
    image: "/images/tesla-model3.jpg",
    location: "Nantes (44)",
    category: "SUV",
    doors: 5, seats: 5, trunkVolume: 854, color: "Noir", drivetrain: "Propulsion",
    euroNorm: "Euro 6d", autonomy: 533, cylinders: "Moteur electrique", weight: 1979,
    vin: "5YJYGDEE4PF123456",
    vinHistory: [
      { date: "04/2023", event: "Premiere immatriculation", mileage: 0, location: "Nantes (44)", status: "info" },
      { date: "04/2024", event: "Revision constructeur - RAS", mileage: 12000, location: "Nantes (44)", status: "ok" },
    ],
  },
]

export const cars: Car[] = rawCars
  .map((car) => ({
    ...car,
    carbonGrade: getGrade(car.co2),
  }))
  .sort((a, b) => a.co2 - b.co2)

export const allCategories: VehicleCategory[] = [
  "Citadine",
  "Berline",
  "SUV",
  "Coupe",
  "Break",
  "Monospace",
  "Utilitaire",
]

export const allFuels = ["Electrique", "Hybride", "Essence", "Diesel"]

export const allLocations = [
  "Paris (75)",
  "Lyon (69)",
  "Marseille (13)",
  "Bordeaux (33)",
  "Toulouse (31)",
  "Nantes (44)",
  "Strasbourg (67)",
  "Lille (59)",
  "Nice (06)",
  "Montpellier (34)",
  "Rennes (35)",
  "Grenoble (38)",
  "Dijon (21)",
  "Tours (37)",
]
